name: 'Lightstep Pre-Deploy Check'
author: 'Lightstep, Inc.'
description: 'Checks health of production environment before deploy'

outputs:
  lightstep_predeploy_md:
    description: 'Markdown summary of pre-deploy checks'

runs:
  using: 'node12'
  main: 'dist/index.js'
